### PR TITLE
Add explicit color management.

### PR DESCRIPTION
**Pull request by lpy**
Color management was introduced in Android O. Currently Fresco allows
applications to specify whether a decoded bitmap should be transformed to SRGB
color space or not at load time, and legacy APIs pass in false, meaning if
applications don't use newer APIs, the decoded bitmap will have the encoded
color space as the final color space if they have one. This doesn't not align
with the world before Android O because before Android O, everything is
essentially treated as SRGB inside the rendering pipeline no matter whether the
images come with a color space.

This patch, 1) Modifies the newer APIs to accept ColorSpace instead of a
boolean, a more future-proof solution as mobile display technology evolves; 2)
Updates legacy APIs to pass in null, meaning on newer devices (API level >=
26), applications that haven't managed color will always get the decoded bitmap
in SRGB color space.

Issue: #2318

### CODE REVIEW

File: imagepipeline-base/src/main/java/com/facebook/imagepipeline/common/ImageDecodeOptionsBuilder.java [hunk 1]
```diff
@@ -197,26 +200,6 @@ public ImageDecodeOptionsBuilder setBitmapConfig(Bitmap.Config bitmapConfig) {
...
-    return mTransformToSRGB;
-  }
-
-  /**
-   * Sets whether to allow or not the color space transformation of the image.
-   *
-   * @param transformToSRGB whether to allow the color space to be transformed to sRGB
-   * @return this builder
-   */
-  public ImageDecodeOptionsBuilder setTransformToSRGB(boolean transformToSRGB) {
```
Comment (oprisnik) [inline imagepipeline-base/src/main/java/com/facebook/imagepipeline/common/ImageDecodeOptionsBuilder.java]: In order to not break the API, we could deprecate this method and just set the color space accordingly (if we decide to support the `null` variant. Otherwise, this will be a no-op I suppose and we can just remove it.

File: imagepipeline/src/main/java/com/facebook/imagepipeline/nativecode/DalvikPurgeableDecoder.java [hunk 2]
```diff
@@ -114,10 +123,14 @@ protected DalvikPurgeableDecoder() {
       Bitmap.Config bitmapConfig,
       @Nullable Rect regionToDecode,
       int length,
-      final boolean transformToSRGB) {
+      @Nullable final ColorSpace colorSpace) {
     BitmapFactory.Options options = getBitmapFactoryOptions(
         encodedImage.getSampleSize(),
         bitmapConfig);
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
+      options.inPreferredColorSpace = colorSpace == null
```
Comment (oprisnik) [inline imagepipeline/src/main/java/com/facebook/imagepipeline/nativecode/DalvikPurgeableDecoder.java]: This check (and the one above) are going to break DEX preverification. Can you instead move these to a util class, similar to this:

```
    ...
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      OreoUtils.setColorSpace(options, colorSpace);
    }
    ...
  }



  ....
  import com.facebook.annotations.DoNotOptimize;
  @DoNotOptimize
  private static class OreoUtils {
    void setColorSpace(...) {
        options.inPreferredColorSpace = ...
    }
  }
}
```

File: imagepipeline/src/main/java/com/facebook/imagepipeline/nativecode/DalvikPurgeableDecoder.java [hunk 3]
```diff
@@ -81,10 +84,14 @@ protected DalvikPurgeableDecoder() {
...
       Bitmap.Config bitmapConfig,
       @Nullable Rect regionToDecode,
-      final boolean transformToSRGB) {
+      @Nullable final ColorSpace colorSpace) {
     BitmapFactory.Options options = getBitmapFactoryOptions(
         encodedImage.getSampleSize(),
         bitmapConfig);
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
+      options.inPreferredColorSpace = colorSpace == null
+              ? ColorSpace.get(ColorSpace.Named.SRGB) : colorSpace;
```
[the remark this answers is not in the document]
Comment (lpy) [reply imagepipeline/src/main/java/com/facebook/imagepipeline/nativecode/DalvikPurgeableDecoder.java]: There's no benefit I can think of to get such behaviour in my humble opinion. One must be very sure about the encoded color space of the contents in order to be confident to skip this bit while also maintain color management in the pipeline. But in that case, the color space is already known in advance, and passing a `ColorSpace` would make the code more readable as well.

File: imagepipeline-base/src/main/java/com/facebook/imagepipeline/common/ImageDecodeOptionsBuilder.java (hunk 1 above)
Comment (lpy) [reply imagepipeline-base/src/main/java/com/facebook/imagepipeline/common/ImageDecodeOptionsBuilder.java]: To make sure this library provides benefit of helping manage color, I would suggest removing this, and don't support the `null` variant.

**Comment by lpy** [comment]
Thanks for the feedback, I resolved the last comment and replied the first two comments.

May I ask how to run the tests locally? Android Studio doesn't seem to allow me to run the tests. :) Also, the `showcase` keep returning `error: cannot find symbol class AnimatedDrawable2` in the latest Android Studio :(

**Comment by oprisnik** [comment]
Yeah, the build was broken (I fixed it with 28de385fea88def78bfab4b59d5d7bf10b9ec83e) and our CI is also still acting up. Using Gradle / Android Studio usually works for test.

I'll import your pull request and do some internal testing. Thanks again!

**Comment by lpy** [comment]
Should I wait for your feedback? May I ask help for CI rerun? I am going to squash into one commit to avoid commit pollution as well.

**Comment by lambdapioneer** [comment]
Ipy, don't worry about merging the commits. It will automatically be merged under the PR request including the summary when we land this internally.

When landing we'll also be auto-formatting the change to reflect our code style. This includes flipping some annotations as our tools assume `@Nonnull` be default. After passing our internal tests, this should land today or tomorrow.
