### ISSUE TITLE
React Native app crashes on startup with fresco version 3.1.3

### ISSUE THREAD

**Issue by erez-unitronics** [facebook/fresco#2751]
Hi,

After updated fresco from v2.6.0 to V3.1.3 my app is crashing on startup.
I get this error:

1-15 16:13:23.049  1918  2016 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
11-15 16:13:23.049  1918  2016 E AndroidRuntime: Process: com.utronmobileapp, PID: 1918
11-15 16:13:23.049  1918  2016 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/drawee/backends/pipeline/info/ImagePerfDataListener;
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at com.utronmobileapp.ReactNativeFlipper.initializeFlipper(ReactNativeFlipper.java:33)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at com.utronmobileapp.MainApplication.onCreate(MainApplication.java:62)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.drawee.backends.pipeline.info.ImagePerfDataListener" on path: DexPathList[[zip file "/data/app/~~9xBMnD66x8c92H7_AgKv0A==/com.utronmobileapp-7arcVo59dgTMFspDjnczEw==/base.apk"],nativeLibraryDirectories=[/data/app/~~9xBMnD66x8c92H7_AgKv0A==/com.utronmobileapp-7arcVo59dgTMFspDjnczEw==/lib/x86_64, /data/app/~~9xBMnD66x8c92H7_AgKv0A==/com.utronmobileapp-7arcVo59dgTMFspDjnczEw==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-15 16:13:23.049  1918  2016 E AndroidRuntime: 	... 13 more

Any ideas why?
It works fine with v2.6.0

This is how i implement it in the build.gradle file:

    def fresco_version = '3.1.3' // Was 2.6.0
    implementation "com.facebook.fresco:fresco:${fresco_version}"
    implementation "com.facebook.fresco:imagepipeline-okhttp3:${fresco_version}"
    implementation "com.facebook.fresco:animated-gif:${fresco_version}"

*React-native version is 0.72.6

Thanks

**Comment by hiThilinaW** [comment]
@erez-unitronics Hello Did you able to find a solution for this

**Comment by erez-unitronics** [comment]
@hiThilinaW Unfortunately no

**Comment by oprisnik** [comment]
Can you try adding a dependency on ui-common, which is the artifact that includes the listener that according to your stack trace cannot be found?

```
implementation "com.facebook.fresco:ui-common:${fresco_version}"
```

https://github.com/facebook/fresco/blob/f528f6bae63e46d351303126f2b1d255ad0c7602/ui-common/gradle.properties

**Comment by erez-unitronics** [comment]
@oprisnik 
Hey, thanks for your reply but still got an error:

--------- beginning of crash
11-26 10:07:57.559 13687 15422 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
11-26 10:07:57.559 13687 15422 E AndroidRuntime: Process: com.kiosk, PID: 13687
11-26 10:07:57.559 13687 15422 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/flipper/plugins/fresco/FrescoFlipperPlugin;
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at com.kiosk.ReactNativeFlipper$2$1.run(ReactNativeFlipper.java:65)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:755)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.facebook.flipper.plugins.fresco.FrescoFlipperPlugin
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	... 7 more
11-26 10:07:57.559 13687 15422 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/drawee/backends/pipeline/info/ImagePerfDataListener;
11-26 10:07:57.559 13687 15422 E AndroidRuntime: 	... 7 more
11-26 10:07:57.559 13687 15422 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.drawee.backends.pipeline.info.ImagePerfDataListener" on path: DexPathList[[zip file "/data/app/com.kiosk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kiosk-1/lib/arm64, /data/app/com.kiosk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]

I also tried to add this line: implementation "com.facebook.fresco:drawee:${fresco_version}"
but it didn't help.

**Comment by Darkty** [comment]
Any update on this? i have the same problem

**Comment by wadiasalem** [comment]
Any update on this

**Comment by stargt** [comment]
Any update?

**Comment by stargt** [comment]
fyi
https://github.com/facebook/fresco/commits/a4ac78a413bb8e5eef6339df0a9a11aadcaed64f/ui-common/src/main/java/com/facebook/fresco/ui/common/ImagePerfDataListener.java

**Comment by parlet** [comment]
_@erez-unitronics, @hiThilinaW, @Darkty, @wadiasalem, @stargt: I'm pinging y'all since you were looking for solutions._

You might want to check out my short write-up in https://github.com/facebook/react-native/issues/41937#issuecomment-1862698593.
In essence:

> […], [ReactNativeFlipper.kt:14](https://github.com/facebook/react-native/blame/1045b225f1a1ab1150b3e8732820c8cecd3e04c2/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/flipper/ReactNativeFlipper.kt#L14) mentions:
> 
> ```kotlin
> /**
>  * Stub class that does nothing to ease the migration out of Flipper. Users should stop calling
>  * `ReactNativeFlipper.initializeFlipper` in their `MainApplication.java` as this class will be
>  * removed in React Native 0.75 or future versions.
>  */
> ```
> 
> And indeed, if the `ReactNativeFlipper.initializeFlipper()` line in `MainApplication.java` is commented-out, the issue is resolved. 🎉

Hope it works for you.🤞

**Comment by sandorbokor** [comment]
I was trying to upgrade from 2.6.0 to 3.1.3 in a regular android  app since I saw there was a new webplib upgrade and hoped that would fix android tv sigsev errors (that is just a hope) and lets say it is not the easiest experience. I needed to add middleware, ui-common , running into ImagePrefDataListener error. Have tried updating flipper too, now having duplicate class declarations between flipper and stetho which we are not using (so must be a transitive dependency I didn't find, but will keep looking)

**Comment by erez-unitronics** [comment]
Issue fixed for me after upgrading React Native to v0.73.1
