### ISSUE TITLE
couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/com.excelliance.multiaccount/gameplugins/com.***.***/lib-main/libimagepipeline.so" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by kartyjoin** [facebook/fresco#2339]
couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/com.excelliance.multiaccount/gameplugins/com.***.***/lib-main/libimagepipeline.so" is 64-bit instead of 32-bit

com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:738)
--
  | com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:591)
  | com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:529)
  | com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:484)
  | com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load (ImagePipelineNativeLoader.java:40)
  | com.facebook.imagepipeline.memory.NativeMemoryChunk. (SourceFile:31)
  | com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc (NativeMemoryChunkPool.java:25)
  | com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc (NativeMemoryChunkPool.java:13)
  | com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc (NativeMemoryChunkPool.java:13)
  | com.facebook.imagepipeline.memory.BasePool.get (BasePool.java:267)
  | com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream. (SourceFile:51)
  | com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream (MemoryPooledByteBufferFactory.java:106)
  | com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream (MemoryPooledByteBufferFactory.java:24)
  | com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream (MemoryPooledByteBufferFactory.java:24)
  | com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse (NetworkFetchProducer.java:96)
  | com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse (NetworkFetchProducer.java:73)
  | com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse (OkHttpNetworkFetcher.java:177)
  | okhttp3.RealCall$AsyncCall.execute (RealCall.java:206)
  | okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
  | java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  | java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  | java.lang.Thread.run (Thread.java:764)

**Comment by oprisnik** [comment]
What devices does this happen on? There's the same issue already open for SoLoader but the other way around (32 bit instead of 64) and using a different Android Gradle Plugin version helped: https://github.com/facebook/SoLoader/issues/29

What version are you using?

**Comment by kartyjoin** [comment]
version:
api "com.facebook.fresco:fresco:1.13.0"
api "com.facebook.fresco:imagepipeline-okhttp3:1.10.0"

**Comment by oprisnik** [comment]
Can you try with the Android Gradle plugin version 3.2.0 as described in the issue I've linked above?

**Comment by chufengma** [comment]
so what is the root cause? 
same problem...

**Comment by oprisnik** [comment]
Does it work with Android Gradle plugin version 3.2.0 as described above?

**Comment by waseefakhtar** [comment]
@oprisnik I have the same issue and I don't think downgrading Android Gradle plugin solves it since we started seeing the issues only after supporting 64-bit architectures.

**Comment by waseefakhtar** [comment]
@oprisnik we use 3.3.2 but only started noticing this issue after supporting 64-bit architectures i.e. replacing:

```
ndk {
            abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
        }
```

with:

```
ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
```

**Comment by waseefakhtar** [comment]
Regarding the devices and OS version, it usually occurs on Oppo and Android 5.1.1

<img width="920" alt="Screen Shot 2019-08-14 at 7 29 12 PM" src="https://user-images.githubusercontent.com/4093820/63029409-f5059b00-bec9-11e9-9f4a-bbd22c33fef3.png">

**Comment by waseefakhtar** [comment]
I tried downgrading from 3.3.2 to 3.2.0 but that fails with build errors due to incompatibility issues with other androidx dependencies.

**Comment by sp00ne** [comment]
```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: ".../lib-main/libimagepipeline.so" is 64-bit instead of 32-bit
```
Got this crash recently in our production app.
Downgrading our gradle version wouldn't cut it as other dependencies require higher. Further, that would not work as a solution either way 😅 

Any update?

**Comment by GlebMaltsev** [comment]
> Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/com.plato.android/lib-1/libimagepipeline.so" is 32-bit instead of 64-bit
>        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
>        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
>        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
>        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
>        ...


classpath 'com.android.tools.build:gradle:3.5.3'
implementation 'com.facebook.fresco:fresco:2.1.0

splits {
        abi {
            ...
            include "x86", "armeabi-v7a", "arm64-v8a"
        }
    }'

70 crashes during last month, 91% - Samsung (where 45% Samsung A20, 23% A70, and 20% S10 and 3% S7), 8% -Infinix NOTE 5 Stylus and 1% BLU GRAND HD

Any updates?

**Comment by SrHalf** [comment]
I have the same problem. Initially in Fresco 1.13.0, and after upgrade to 2.0.0.

E/SoLoader: couldn't find DSO to load: libimagepipeline.so
E/AndroidRuntime: FATAL EXCEPTION: FrescoIoBoundExecutor-2
    Process: my.package.xxx, PID: 4382
    java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.imagepipeline.memory.NativeMemoryChunk; see exception in other thread
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)

**Comment by otopba** [comment]
Any updates?

**Comment by ishroid** [comment]
Any update ,i am still having same issue with latest version in android bundle only.

**Comment by sebastian-hoebarth** [comment]
Is there a gradle bundle hot fix or something? 

`Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/com.megalol.app/lib-0/libimagepipeline.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:918)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
       at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:33)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:31)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:16)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:256)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:55)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:108)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:25)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:98)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:75)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:191)
       at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:71)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)`

**Comment by MaxJadav** [comment]
@sebastian-hoebarth  Getting same crash Do you have any solution?
Brand:OnePlus
Model:OnePlus8Pro
Version:Android 11

`Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.disctopia.android/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0 result: 0 result: 0`

I already include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
But still getting this crash

**Comment by waseefakhtar** [comment]
Our production app _still_ experiences this. Looks like it was never fixed.
